### ISSUE TITLE
 Connection.php

### ISSUE THREAD

**Issue by SBYDeveloper** [madewithpepper/Pulse-Proximity-Platform#1]
### Version
0.1.0

### Steps to reproduce
1.  After starting the installation process two errors occur

`QueryException in Connection.php line 647:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `expires` datetime null, `created_at` timestamp null, `updated_at` ti' at line 1 (SQL: create table `resellers` (`id` int unsigned not null auto_increment primary key, `api_token` varchar(60) null, `name` varchar(32) not null, `domain` varchar(250) not null, `default_language` varchar(5) not null default 'en', `default_timezone` varchar(32) not null default 'UTC', `mail_from_address` varchar(64) null, `mail_from_name` varchar(64) null, `mail_driver` varchar(32) null, `mail_host` varchar(150) null, `mail_port` varchar(5) null, `mail_encryption` varchar(5) null, `mail_mailgun_domain` text null, `mail_mailgun_secret` text null, `mail_username` text null, `mail_password` text null, `page_title` varchar(250) null, `favicon` varchar(250) null, `logo` varchar(250) null, `logo_square` varchar(250) null, `avangate_sandbox` tinyint(1) not null default '0', `avangate_key` text null, `stripe_sandbox` tinyint(1) not null default '0', `stripe_key` text null, `stripe_secret` text null, `braintree_sandbox` tinyint(1) not null default '0', `braintree_merchant_id` text null, `braintree_public_key` text null, `braintree_private_key` text null, `active` tinyint(1) not null default '1', `settings` json null, `expires` datetime null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci)`

`PDOException in Connection.php line 445:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `expires` datetime null, `created_at` timestamp null, `updated_at` ti' at line 1`

**Comment by skokhuis** [comment]
What MySQL version do you use? The platform requires >= 5.7 because it uses JSON data type (https://dev.mysql.com/doc/refman/5.7/en/json.html).

**Comment by SBYDeveloper** [comment]
I have to check. I think its 5.7(not sure since we are making the installation on Godaddy VPS). Let me see and i will get back to you.

**Comment by SBYDeveloper** [comment]
Yes so its Server version: 5.6.33-cll-lve - MySQL Community Server (GPL)... Godaddy... i will try to talk to them to explain us how as we have VPS there to make the update
