### ISSUE TITLE
File disappears 

### ISSUE THREAD

**Issue by ormit** [madewithpepper/Pulse-Proximity-Platform#2]
when i try and edit the config file name  core/.env.example to .env  it disappears 👍

**Comment by skokhuis** [comment]
Sounds like you're using Windows :)

https://madewithpepper.com/docs/v0.1/platform/installation
> In Windows, you have to enter a space and a dot after `.env` to rename the file. Like this: `.env .` and press enter.

**Comment by ormit** [comment]
created the file on the server and it still disappeared (plesk)

**Comment by ormit** [comment]
sorted : env.env .

**Comment by skokhuis** [comment]
OK, great
