### ISSUE TITLE
Shared hosting

### ISSUE THREAD

**Issue by kimmoda** [madewithpepper/Pulse-Proximity-Platform#3]
Hello , ı can install this project to shared host ?

thanks

**Comment by skokhuis** [comment]
Yes. If the server requirements are met it, should work on shared hosting. The Laravel public dir has been moved to the root for that purpose.

**Comment by kimmoda** [comment]
thanks , but when ı try install shared hosting , i get some database errors.how to fix that ?

**Comment by kimmoda** [comment]
http://www.vaggon.com/ see.

**Comment by skokhuis** [comment]
It looks your MySQL version is < 5.7.8: https://github.com/madewithpepper/Pulse-Proximity-Platform/issues/1

**Comment by kimmoda** [comment]
![testlocal](https://cloud.githubusercontent.com/assets/24658354/24832823/35871df0-1cc1-11e7-818b-b388df060b91.PNG)

in my localhost also not working , this error . and localhost ı see Whoops, looks like something went wrong. error

**Comment by skokhuis** [comment]
If you see "Whoops", set debug to true in .`env` file in order to see the full error.
I've never seen the "could not find driver" error before, what's the context? And what driver did you configure?

**Comment by kimmoda** [comment]
ı fixed db problem . but now ı get this error 

FatalErrorException in Encrypter.php line 78:
Call to undefined function openssl_encrypt()

**Comment by skokhuis** [comment]
Make sure the OpenSSL extension is installed.

**Comment by kimmoda** [comment]
ok , i install my localhost . working but not like this  and not functional https://demo.pulseplatform.io/login

**Comment by kimmoda** [comment]
![home1](https://cloud.githubusercontent.com/assets/24658354/24871646/fe60d830-1e22-11e7-9cfa-7ba82750ceeb.PNG)

**Comment by kimmoda** [comment]
![home2](https://cloud.githubusercontent.com/assets/24658354/24871711/377e3be4-1e23-11e7-81eb-1b0f61658152.PNG)

**Comment by skokhuis** [comment]
That's a commercial version. This is rewritten from scratch with the latest frameworks. And it is functionial, but not yet production ready as written on the madewithpepper.com homepage. The screenshots on madewithpepper.com are also different than the demo.

The images weren't in the repo because of .gitignore, they're added now. For other issues please open a new ticket.
