### ISSUE TITLE
Install pulse platform

### ISSUE THREAD

**Issue by soares02** [madewithpepper/Pulse-Proximity-Platform#4]
### Version
0.1.0

### Steps to reproduce
1.  
2.  
3.  

### Expected behavior
What should happen

### Actual behavior
What is happening

I installed pulse platform locally with wampserver.
The installation is done without problem, but when I click in the menu, nothing is displayed, only the menu bar appears

http://c2n.me/3JoOvv4

thank you

**Comment by skokhuis** [comment]
Did you install in a subdirectory? For now it's only possible to install in web root of domain or subdomain.

**Comment by soares02** [comment]
Is work fine now ;)

thanks you for your help

**Comment by skokhuis** [comment]
YW! The system will probably change a lot the coming time, there are still many things to do :)

**Comment by soares02** [comment]
Thank you very much for having done pulse platform open source, this is for me a great project with a lot of future.
