### ISSUE TITLE
Request failed, please try again (error)

### ISSUE THREAD

**Issue by ormit** [madewithpepper/Pulse-Proximity-Platform#5]
### Version
0.1.0

### Steps to reproduce
1.  create campaign
2.  add scenario
3.  error message : Request failed, please try again (error)

### Expected behavior
add scenario
<img width="1064" alt="screen shot 2017-04-17 at 15 25 17" src="https://cloud.githubusercontent.com/assets/1593005/25091643/277d4f50-2382-11e7-91ef-301f59e0813b.png">

### Actual behavior
 error message appears : Request failed, please try again (error)

**Comment by skokhuis** [comment]
What does the dev console say? And is it the first thing you do on a fresh installation? It seems to work fine on the demo, so maybe it's related to your MySQL version or a session time-out.

**Comment by ormit** [comment]
Will try a fresh install of the solution with a new SQL database, It was last week when I installed. 

 

Best Reagrds

 

Tim

**Comment by skokhuis** [comment]
Okay. The creation of a scenario works with JWT, so my guess is that the session was expired and refreshing the page might have solved it.

**Comment by ormit** [comment]
hi , it looks like it was the old DB  , as soon as i created a new database and started from fresh it worked fine .  Hows this going to work going forward if their are any changes now to the DB structure ?
