### ISSUE TITLE
Installing on Ubuntu 16.04 from Parallels/VirtualBox Virtual Machine

### ISSUE THREAD

**Issue by mangopudding** [madewithpepper/Pulse-Proximity-Platform#6]
### Version
0.1.0

### Steps to reproduce
**1.  Installing Ubuntu 16.04 server in Parallels or VirtualBox environment**
_This was a fresh install with just SSH services._

**2. Installing PHP 5.6**

`sudo add-apt-repository ppa:ondrej/php`
`sudo apt-get update`
`sudo apt-get install python-software-properties`
`sudo apt-get install php5.6 `
`sudo apt-get install php5.6-zip`
`sudo apt-get install php5.6-intl`
`sudo apt-get install php5.6-mcrypt`
`sudo apt-get install php5.6-curl`
`sudo apt-get install php5.6-mbstring`
`sudo apt-get install php5.6-gd`
`sudo apt-get install php5.6-xml`
`sudo apt-get install php5.6-mysql`
`sudo apt-get install php5.6-sql3lite`

**3.  Installing MySQL Server 5.7.17**
`sudo apt-get install mysql-server`

- Remember to have “strict mode disabled”
- [Instructions on how to Disable Strict Mode In MySQL 5.7](https://serverpilot.io/community/articles/how-to-disable-strict-mode-in-mysql-5-7.html)

**4. Installing Laravel Framework**

- Do I need to do that?  I just need some direction on what to do here.

**5. Apache Configuration**

- Remember to enable mod_rewrite module.
- If everything in installed on /var/www/html/ ,what should my Apache config file look like?

### Expected behavior
Getting website to load

### Actual behavior
Website not loading

**Comment by mangopudding** [comment]
My objective above is to be able to create some accurate installation documentation and a create a installation script getting the open source version of this project running in a virtual machine locally on my Mac.  :)

**Comment by skokhuis** [comment]
I'd advice to use PHP 7. Is there anything in the log (`core/storage/logs/laravel.log`)? And did you create a VirtualHost like `pulse.test`?

**Comment by mangopudding** [comment]
Hi SK.  I installed PHP 7.

I went into `/var/www/html/core/` and ran `php artisan key:generate`.

I can see that the `.env` file in `/var/www/html/core/` had the new the APP_KEY in there.

I also went into `/var/www/html/core/config/app.php` and added the new key in the respective Encryption Key section.

When I try to go to my site, I get the following in my laravel.log:

`RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. `

Looking at some Google searches, I also tried:

`php artisan key:generate`
`php artisan config:clear`
`php artisan config:cache`

For the **Apache config file**, I'm just using the default one from `/etc/apache2/sites-available/000-default.conf`

Do I need to change the **DocumentRoot** to be something other than `/var/www/html`  ?

**Comment by skokhuis** [comment]
The key error is related to Laravel, I don't know what's the cause in your case if the `.env` file has a correct key: https://laravel.io/forum/06-04-2015-cipher-error

**Comment by mangopudding** [comment]
Hi.

I noticed in the .env file that it mentions that the installer will generate the key.

Since I was trying to do the  `php artisan key:generate` command - that's what's probably messing stuff up.

So I followed your instructions and how I get to `http://<url>/login` 

But it says "**Not Found**".

Nothing in the` /var/www/html/core/storage/logs/` and I don't see any errors in the Apache logs.

**Can you post an example of what your Apache virtual host looks like please.**

I'm installing everything from` /var/www/html/`

**Comment by mangopudding** [comment]
I'm making some progress!

```
<VirtualHost *:80>
    ServerName pulse.mydomain.com

    ServerAdmin no-reply@mydomain.com

    DocumentRoot /var/www/html/pulse/

    <Directory /var/www/html/pulse>
        AllowOverride All
	Options FollowSymLinks
	Order allow,deny
	allow from all
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

**Comment by mangopudding** [comment]
I ran into this error:

`production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function Hashids\bcmod() `

Based on the PHP 7 installation, there's additional libraries that are needed like these:

`sudo apt-get install php-bcmath`
`sudo apt-get install php-amqplib`

**Comment by mangopudding** [comment]
I can now log in and it's working now!

I'm going to spend some time and write up the installation steps and post it here.

**Comment by mangopudding** [comment]
The steps below are what I've used to install this cool project on **Ubuntu 16.04 server**.  I've tested these steps on a local virtual machine on my Mac running Parallels but have also spun up an` Amazon Web Services EC2 Instance of Ubuntu 16.04 server`.

Hope this helps those who are interested in trying out this cool open source project!

-----

Install Ubuntu Tasksel Utility
`sudo apt-get install tasksel`

Install LAMP Stack via Ubuntu Tasksel
Remember your root password for MySQL
`sudo tasksel`

Verify the version of Apache installed
`sudo apache2 -v`

Verify the version of MySQL installed
`sudo mysql --version`

Verify the version of PHP installed
`sudo php -v`

Install Additional PHP Libaries Required For This Project
`sudo apt-get install php-mcrypt php-curl php-mbstring php-xml php-gd php-intl php-zip php-bcmath php-amqplib`


Verify the required PHP libraries are installed
`php -m`

Disable Strict Mode In MySQL 5.7
This is a requirement on MySQL 5.7 at this time.
Use the following tech note: [https://serverpilot.io/community/articles/how-to-disable-strict-mode-in-mysql-5-7.html](url)


Create Database for Pulse
Hope you remember the MysQL root password when you installed LAMP Stack via Tasksel
Steps below to log into mysql commandline, create a database called "pulse", verify that it exists after creation and exit out of mysql commandline.
`mysql -u root -p`
`CREATE DATABASE pulse;`
`SHOW DATABASES;`
`exit`

Create a folder called pulse and go into that directory
`sudo mkdir /var/www/html/pulse`
`cd /var/www/html/pulse`

Download the Pulse Proximity Platform from GitHub
`sudo git clone https://github.com/madewithpepper/Pulse-Proximity-Platform.git .`

Folder Permissions
Make sure these folders are writable:
NEED TO GET TEAM TO VERIFY THIS REQUIREMENT
`sudo chmod 777 -R /var/www/html/pulse/assets/`
`sudo chmod 777 -R /var/www/html/pulse/uploads/`
`sudo chmod 777 -R /var/www/html/pulse/core/bootstrap/cache/`
`sudo chmod 777 -R /var/www/html/pulse/core/storage/ `

Configuration File
Copy the configuration file and update it with the database, mail and Google Maps key info.
`sudo cp /var/www/html/pulse/core/.env.example /var/www/html/pulse/.env`
`sudo vi /var/www/html/pulse/.env`

Create an Apache Virtual Host called pulse.conf
`sudo vi /etc/apache2/sites-available/pulse.conf`

The contents of **pulse.conf** is:
Make note of the directory **/var/www/html/pulse**
```
<VirtualHost *:80>
    ServerName pulse.mydomain.com

    ServerAdmin no-reply@mydomain.com

    DocumentRoot /var/www/html/pulse/

    <Directory /var/www/html/pulse>
        AllowOverride All
	Options FollowSymLinks
	Order allow,deny
	allow from all
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

Enable mod_re-write on Apache 
`sudo a2enmod rewrite`


Restart Apache Services
`sudo service apache2 restart`


Disable Default Apache Virtual Host Profile
`sudo a2dissite 000-default.conf `


Enable Virtual Host Profile on Apache
`sudo a2ensite pulse.conf `


Reload Apache Services
`sudo service apache2 reload`


Now, you should able able to launch your browser and complete the installation!

**Comment by skokhuis** [comment]
Thanks a lot for sharing and the effort! I will add this to the docs and credit you.

I will also update the comments because the installation doesn't generate the key anymore. This triggered an error after updating to Laravel 5.4.
