### ISSUE TITLE
QueryException in Connection.php line 647: SQLSTATE[42000]: Syntax error or access violation: 1064 

### ISSUE THREAD

**Issue by karthikindia** [madewithpepper/Pulse-Proximity-Platform#7]
### Version
0.1.0

### Steps to reproduce - using cpanel
1.  upload all files to the webroot
2. changed all file permissions to 777
attachments/
uploads/
core/bootstrap/cache/
core/storage/
3. changed core/.env.example to .env  
4. Created Database assigned db user added into env file 

### Expected behavior
The database should be migrated and seeded automatically

### Actual behavior
http://bcon3.cobrasoftwares.in/
QueryException in Connection.php line 647:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax;

**Comment by karthikindia** [comment]
I saw that there is only one table created in my db named "Migrations" with follwoing fields 	

- id	
- migration
- batch
and no values

**Comment by mangopudding** [comment]
Hi karthikindia!

Do you know what version of MySQL you are using?  

Based on what I had experienced during my setup on Ubuntu 16.04 server, you need to be using a specific version of MySQL Server (5.7.17) and also remember to have “strict mode disabled”

Use the following tech note: https://serverpilot.io/community/articles/how-to-disable-strict-mode-in-mysql-5-7.html

Take a look at my [notes on getting this software deployed on a Ubuntu 16.04 server](https://github.com/madewithpepper/Pulse-Proximity-Platform/issues/6) - it might help you with your installation process.
